name: Publish Dev Library

on:
  push:
    branches:
      - dev

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Configure version as SNAPSHOT
        run: |
          RP_VERSION=$(jq -r '."." // "1.0.0"' .release-please-manifest.json)
          sed -i 's/version.*/version '"'$RP_VERSION-SNAPSHOT'"'/' ./camerasdk/build.gradle

      - name: Publish to GitHub Packages
        run: ./gradlew publish
        env:
          GH_USERNAME: ${{ github.actor }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
      
      - name: Request Snapshot Build for Dev
        run: |
          JITPACK_URL="https://jitpack.io/com/github/fibricheck/android-camera-sdk/dev-SNAPSHOT/"
          # timeout in 30 seconds to avoid waiting for build
          curl -s -m 30 ${JITPACK_URL} || true
