on:
    push:
      branches:
        - main

permissions:
    contents: write
    pull-requests: write

name: Release

jobs:
    release-new-version:
        runs-on: ubuntu-latest
        steps:
        - uses: google-github-actions/release-please-action@v3
          id: release
          with:
            release-type: simple
            extra-files: |
              README.md
              FibriCheckCameraSDK.podspec
              fibricheck-camera-sdk/build.gradle
        outputs:
          release_created: ${{ steps.release.outputs.release_created }}
    publish-package:
        runs-on: ubuntu-latest
        needs: release-new-version
        if: ${{needs.release-new-version.outputs.release_created}}
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v2
            - name: Set up JDK 11
              uses: actions/setup-java@v2 
              with:
                java-version: '11'
                distribution: 'adopt'
            - name: Grant execute permission for gradlew
              run: chmod +x gradlew
            - name: Build
              run: ./gradlew clean build
            # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
            # the publishing section of your build.gradle
            - name: Publish to GitHub Packages
              run: ./gradlew publish
              env:
                GH_USERNAME: ${{ github.actor }}
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
   